- name: Ansible create repo
  copy:
    dest: "/etc/yum.repos.d/MariaDB.repo"
    content: |
      [mariadb]
      name=MariaDB
      baseurl=http://yum.mariadb.org/10.2/centos7-amd64
      gpgkey=https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
      gpgcheck=1

- name: MariaDB packages are installed
  yum:
    pkg: '{{ item }}'
    state: installed
  with_items:
    - mariadb
    - mariadb-server

- name: stop service mariadb on debian, if running
  systemd:
    name: mariadb
    state: stopped
